### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by bolte-io** [demurgos/appdata-path#1]
appdata-path\lib\index.js:59
SyntaxError: Unexpected token )

`
module.exports = Object.assign(
  getAppDataPath,
  {
    getAppDataPath: getAppDataPath,
    default: getAppDataPath, 
  }, 
);
`
Removing comma's at the end of the JSON object resolves the issue, but each time I add/remove a package the error is reinstated.

**Comment by demurgos** [comment]
Hi,
It looks like you're trying to use this package with an environment that does not support JavaScript ES2015 syntax. It corresponds to Node.js version older than Node.js 4. These versions are no longer maintained and I strongly encourage you to update to a newer version. [Check the support for Node versions](https://github.com/nodejs/Release).
